
FROM maven:3.9.6-eclipse-temurin-17-alpine AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar ecomarket-catalogo.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "ecomarket-catalogo.jar"]